In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('Bengaluru_House_Data.csv')
df.head()

Mounted at /content/drive
/content/drive/MyDrive

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [3]:
for column in df.columns:
  print(df[column].value_counts())
  print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
SLtalry     1
Rencyes     1
DiaveEn     1
Suiumy      1
Amionce     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [4]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [5]:
df.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [6]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [8]:
df['location']=df['location'].fillna('Sarjapur Road')

In [9]:
df['size']=df['size'].fillna('2 BHK')

In [10]:
df['bath']=df['bath'].fillna(df['bath'].median())

In [11]:
df['bhk']=df['size'].str.split().str.get(0).astype(int)

In [12]:
def convertrange(x):
  t=x.split('-')
  if len(t)==2:
    return (float(t[0])+float(t[1]))/2
  try:
     return float(x)
  except:
    return None

In [13]:
df['total_sqft'].unique()
df['total_sqft']=df['total_sqft'].apply(convertrange)

In [14]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [15]:
#buiding price per sq ft coloumn
df['price_per_sqft']=df['price']*100000/df['total_sqft']
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [16]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [17]:
df['location'].value_counts()

location
Whitefield                  540
Sarjapur  Road              399
Electronic City             302
Kanakpura Road              273
Thanisandra                 234
                           ...
Mango Garden Layout           1
Milk Colony                   1
Basnashankari,6th stage,      1
Near ullas theater            1
N R Layout                    1
Name: count, Length: 1306, dtype: int64

In [18]:
df['location']=df['location'].apply(lambda x:x.strip())
location_count=df['location'].value_counts()
df['location_count']=df['location'].apply(lambda x:location_count[x])
df[df['location_count']<=10]

,location,size,total_sqft,bath,price,bhk,price_per_sqft,location_count
9,Gandhi Bazar,6 Bedroom,1020.0,6.0,370.00,6,36274.509804,2
18,Ramakrishnappa Layout,3 BHK,2770.0,4.0,290.00,3,10469.314079,7
19,Manayata Tech Park,2 BHK,1100.0,2.0,48.00,2,4363.636364,8
25,Mangammanapalya,3 BHK,1250.0,3.0,56.00,3,4480.000000,3
42,Ganga Nagar,1 BHK,600.0,1.0,38.00,1,6333.333333,10
...,...,...,...,...,...,...,...,...
13291,Weavers Colony,1 Bedroom,812.0,1.0,26.00,1,3201.970443,3
13292,Udayapur Village,3 BHK,1440.0,2.0,63.93,3,4439.583333,4
13302,Annaiah Reddy Layout,2 BHK,1075.0,2.0,48.00,2,4465.116279,2
13306,Rajarajeshwari Nagara,4 Bedroom,1200.0,5.0,325.00,4,27083.333333,3
13316,Richards Town,4 BHK,3600.0,5.0,400.00,4,11111.111111,7

In [19]:
df['location']=df['location'].apply(lambda x:'other' if x in location_count[location_count<=10] else x)
df['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [20]:
#outlier detection
df.describe()

,total_sqft,bath,price,bhk,price_per_sqft,location_count
count,13274.000000,13320.000000,13320.000000,13320.000000,1.327400e+04,13320.000000
mean,1559.626694,2.688814,112.565627,2.802778,7.907501e+03,96.512462
std,1238.405258,1.338754,148.971674,1.294496,1.064296e+05,130.340926
min,1.000000,1.000000,8.000000,1.000000,2.678298e+02,1.000000
25%,1100.000000,2.000000,50.000000,2.000000,4.266865e+03,13.000000
50%,1276.000000,2.000000,72.000000,3.000000,5.434306e+03,43.000000
75%,1680.000000,3.000000,120.000000,3.000000,7.311746e+03,132.000000
max,52272.000000,40.000000,3600.000000,43.000000,1.200000e+07,541.000000

In [21]:
df[df.total_sqft/df.bhk<300].head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft,location_count
9,other,6 Bedroom,1020.0,6.0,370.0,6,36274.509804,2
45,HSR Layout,8 Bedroom,600.0,9.0,200.0,8,33333.333333,53
58,Murugeshpalya,6 Bedroom,1407.0,4.0,150.0,6,10660.980810,14
68,Devarachikkanahalli,8 Bedroom,1350.0,7.0,85.0,8,6296.296296,17
70,other,3 Bedroom,500.0,3.0,100.0,3,20000.000000,1

In [22]:
df=df[((df['total_sqft']/df['bhk'])>=300)]
df.describe()

,total_sqft,bath,price,bhk,price_per_sqft,location_count
count,12530.000000,12530.000000,12530.000000,12530.000000,12530.000000,12530.000000
mean,1594.564544,2.559537,111.382401,2.650838,6303.979357,100.221868
std,1261.271296,1.077938,152.077329,0.976678,4162.237981,132.497053
min,300.000000,1.000000,8.440000,1.000000,267.829813,1.000000
25%,1116.000000,2.000000,49.000000,2.000000,4210.526316,14.000000
50%,1300.000000,2.000000,70.000000,3.000000,5294.117647,47.000000
75%,1700.000000,3.000000,115.000000,3.000000,6916.666667,142.000000
max,52272.000000,16.000000,3600.000000,16.000000,176470.588235,541.000000

In [23]:
def removeoutliers(df):
  dfout=pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m=np.mean(subdf.price_per_sqft)
    st=np.std(subdf.price_per_sqft)
    gdf=subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
    dfout=pd.concat([dfout,gdf], ignore_index=True)
  return dfout
df=removeoutliers(df)

In [24]:
df.describe()

,total_sqft,bath,price,bhk,price_per_sqft,location_count
count,10301.000000,10301.000000,10301.000000,10301.000000,10301.000000,10301.000000
mean,1508.440608,2.471702,91.286372,2.574896,5659.062876,101.392777
std,880.694214,0.979449,86.342786,0.897649,2265.774749,135.128590
min,300.000000,1.000000,10.000000,1.000000,1250.000000,1.000000
25%,1110.000000,2.000000,49.000000,2.000000,4244.897959,13.000000
50%,1286.000000,2.000000,67.000000,2.000000,5175.600739,47.000000
75%,1650.000000,3.000000,100.000000,3.000000,6428.571429,142.000000
max,30400.000000,16.000000,2200.000000,16.000000,24509.803922,541.000000

In [25]:
def outlierbhk(df):
  excludeindices=np.array([])
  for location,locationdf in df.groupby('location'):
    bhk_stats={}
    for bhk,bhkdf in locationdf.groupby('bhk'):
      bhk_stats[bhk]={
          'mean':np.mean(bhkdf.price_per_sqft),
          'std':np.std(bhkdf.price_per_sqft),
          'count':bhkdf.shape[0]
      }
    for bhk,bhkdf in locationdf.groupby('bhk'):
      stats=bhk_stats.get(bhk-1)
      if stats and stats['count']>5:
        excludeindices=np.append(excludeindices,bhkdf[bhkdf.price_per_sqft<(stats['mean'])].index.values)
  return df.drop(excludeindices,axis='index')

In [26]:
df=outlierbhk(df)

In [27]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft,location_count
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860,14
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491,14
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333,14
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333,14
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668,14

In [28]:
df.drop(columns=['size','price_per_sqft'],inplace=True)

In [29]:
#CLEANED DATA
df.to_csv('Cleaned_data.csv')

In [30]:
x=df.drop(columns=['price'])
y=df['price']

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [32]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [36]:
#linearregression
one_hot_encoder = OneHotEncoder()
column_trans=make_column_transformer((one_hot_encoder,['location']),remainder='passthrough')
scaler=StandardScaler(with_mean=False)
lr=LinearRegression()
pipe=make_pipeline(column_trans,scaler,lr)
pipe.fit(X_train,Y_train)
y_pred_lr=pipe.predict(X_test)

In [37]:
#R2 SCORE
from sklearn.metrics import r2_score
r2_score(Y_test,y_pred_lr)

0.8240495183377997

In [39]:
#applying lasso
lasso=Lasso()
pipe=make_pipeline(column_trans,scaler,lasso)
pipe.fit(X_train,Y_train)
y_pred_lasso=pipe.predict(X_test)
r2_score(Y_test,y_pred_lasso)

0.8128285650772716

In [41]:
#ridge
ridge=Ridge()
pipe=make_pipeline(column_trans,scaler,ridge)
pipe.fit(X_train,Y_train)
y_pred_ridge=pipe.predict(X_test)
r2_score(Y_test,y_pred_ridge)

0.8233937336125676

In [43]:
print("No Regularization: ",r2_score(Y_test,y_pred_lr))
print("Lasso: ",r2_score(Y_test,y_pred_lasso))
print("Ridge: ",r2_score(Y_test,y_pred_ridge))

No Regularization:  0.8240495183377997
Lasso:  0.8128285650772716
Ridge:  0.8233937336125676

In [44]:
import pickle

In [45]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))